### ISSUE TITLE
Python/Django?

### ISSUE THREAD

**Issue by nipython** [mk-fg/blog#1]
Здравствуйте, Михаил!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python от 2-х лет до 100 лет (а опыт с Python-ом у вас есть, судя по репозиторию :), пониманием веба, опытом в Django, возможностью разговаривать хотя бы на ломаном английском :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас И вам было бы интересно переехать в Минск работать в штате компании на лучших условиях (удаленно мы не можем, увы).
Спасибо

**Comment by mk-fg** [comment]
День добрый.

Странно действительно что пишете на github, т.к. email ведь есть что на блоге что на гитхабе томже.
Увы, совсем не интересно, т.к. webdev не люблю чем дальше тем больше, да и переезд (неважно куда) не рассматриваю.
Но удачи с другими кандидатами, уверен что я с такими интересами в меньшинстве :)

Спасибо за предложение.

**Comment by mk-fg** [comment]
P.S.
А, да, наверно очевидно (иначе бы не извинялись), но не пишите в github такие вещи - первое впечатление вроде важнее практически всего остального в общении, а так сразу настраиваете человека против себя, явно показывая непонимание и наплевательское отношение (особенно если email итак на каждом углу висит).
Если бы впринципе была работа интересна, я бы наверно отказался только по этой причине - ну нафиг работать с людьми которые готовы настолько на все настрать.
